### ISSUE TITLE
 Sync does not pull configurations for all Mullvad servers.

### ISSUE THREAD

**Issue by aTosser** [jamesmcm/vopono#197] opened 2022-12-24 18:31 UTC
After performing sync I do not have configurations for all active Mullvad servers. There seem the be ommisions when compared to the server status webpage. 

There also seems to be a new naming convention in use for Mullvad servers.

**Comment by jamesmcm** [comment] 2023-01-02 12:45
Thanks, I'll take a look.

**Comment by jamesmcm** [comment] 2023-01-06 10:53
Thanks, the issue is the change in naming convention meaning that active servers for the same city just overwrite eachother.

I'll try to fix it today, at least they are only redundant servers though.

**Comment by jamesmcm** [comment] 2023-05-05 20:49
Fixed in https://github.com/jamesmcm/vopono/commit/29af9f8e1c4e67235264c86f9013f917b377715f

**Closed by jamesmcm** 2023-05-05 20:49 UTC
