### ISSUE TITLE
Cannot resolve PIA address

### ISSUE THREAD

**Issue by cjordan** [jamesmcm/vopono#1] opened 2020-06-27 00:42 UTC
Hi!  I just tried `vopono` with my PIA subscription, but it appears that the connection isn't getting properly established, or something.  The chrome window just complains that there's no internet available.  Any ideas?

```
$ vopono -v exec --provider privateinternetaccess --server nz "/usr/bin/google-chrome-stable"
 2020-06-27T00:37:29.718Z DEBUG users::base > Running getuid
 2020-06-27T00:37:29.718Z DEBUG users::base > Running getpwuid_r for user #1000
 2020-06-27T00:37:29.718Z DEBUG users::base > Loading user with uid 1000
 2020-06-27T00:37:29.718Z DEBUG vopono::util > Cleaning dead lock files...
 2020-06-27T00:37:29.728Z INFO  vopono       > Calling sudo for elevated privileges, current user will be used as default user
 2020-06-27T00:37:29.728Z DEBUG vopono       > Args: ["vopono", "-v", "exec", "--provider", "privateinternetaccess", "--server", "nz", "/usr/bin/google-chrome-stable"]
 2020-06-27T00:37:29.734Z DEBUG vopono::util > Cleaning dead lock files...
 2020-06-27T00:37:29.745Z DEBUG vopono::network_interface > ip addr
 2020-06-27T00:37:29.745Z DEBUG vopono                    > Interface: eth0
 2020-06-27T00:37:29.746Z DEBUG vopono::util              > Existing namespaces: []
 2020-06-27T00:37:29.746Z DEBUG vopono::util              > ip netns add vopono_pia_nz
 2020-06-27T00:37:29.749Z DEBUG vopono::util              > Existing interfaces:
 2020-06-27T00:37:29.749Z DEBUG vopono::util              > Assigned IPs: []
 2020-06-27T00:37:29.749Z DEBUG vopono::vpn               > Read auth file: /home/chj/.config/vopono/pia/openvpn/auth.txt
 2020-06-27T00:37:29.749Z DEBUG vopono::netns             > ip netns exec vopono_pia_nz ip addr add 127.0.0.1/8 dev lo
 2020-06-27T00:37:29.751Z DEBUG vopono::netns             > ip netns exec vopono_pia_nz ip link set lo up
 2020-06-27T00:37:29.753Z DEBUG vopono::util              > ip link add _pia_nz_d type veth peer name _pia_nz_s
 2020-06-27T00:37:29.754Z DEBUG vopono::util              > ip link set _pia_nz_d up
 2020-06-27T00:37:29.755Z DEBUG vopono::util              > ip link set _pia_nz_s netns vopono_pia_nz up
 2020-06-27T00:37:29.805Z DEBUG vopono::util              > ip addr add 10.200.1.1/24 dev _pia_nz_d
 2020-06-27T00:37:29.806Z DEBUG vopono::netns             > ip netns exec vopono_pia_nz ip addr add 10.200.1.2/24 dev _pia_nz_s
 2020-06-27T00:37:29.808Z DEBUG vopono::netns             > ip netns exec vopono_pia_nz ip route add default via 10.200.1.1 dev _pia_nz_s
 2020-06-27T00:37:29.809Z DEBUG vopono::util              > iptables -t nat -A POSTROUTING -s 10.200.1.0/24 -o eth0 -j MASQUERADE
 2020-06-27T00:37:29.810Z DEBUG vopono::util              > sysctl -q net.ipv4.ip_forward=1
 2020-06-27T00:37:29.811Z DEBUG vopono::vpn               > Chosen server: nz.privateinternetaccess.com:1198
 2020-06-27T00:37:29.811Z DEBUG vopono::openvpn           > OpenVPN config: "/home/chj/.config/vopono/pia/openvpn/client.conf"
 2020-06-27T00:37:29.811Z INFO  vopono::openvpn           > Launching OpenVPN...
 2020-06-27T00:37:29.811Z DEBUG vopono::netns             > ip netns exec vopono_pia_nz openvpn --config /home/chj/.config/vopono/pia/openvpn/client.conf --remote nz.privateinternetaccess.com 1198 --auth-user-pass /home/chj/.config/vopono/pia/openvpn/auth.txt --ca /home/chj/.config/vopono/pia/openvpn/ca.rsa.2048.crt --crl-verify /home/chj/.config/vopono/pia/openvpn/crl.rsa.2048.pem
Sat Jun 27 08:37:29 2020 OpenVPN 2.4.9 [git:makepkg/9b0dafca6c50b8bb+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Apr 20 2020
Sat Jun 27 08:37:29 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
Sat Jun 27 08:37:29 2020 CRL: loaded 1 CRLs from file /home/chj/.config/vopono/pia/openvpn/crl.rsa.2048.pem
Sat Jun 27 08:37:35 2020 RESOLVE: Cannot resolve host address: nz.privateinternetaccess.com:1198 (Temporary failure in name resolution)
 2020-06-27T00:37:39.812Z DEBUG vopono                    > Checking that OpenVPN is running in namespace: vopono_pia_nz
 2020-06-27T00:37:39.821Z DEBUG vopono::netns             > Writing lockfile: /home/chj/.config/vopono/locks/vopono_pia_nz
 2020-06-27T00:37:39.821Z DEBUG vopono::netns             > Lockfile written: /home/chj/.config/vopono/locks/vopono_pia_nz/13727
 2020-06-27T00:37:39.822Z DEBUG vopono::netns             > ip netns exec vopono_pia_nz sudo -u chj /usr/bin/google-chrome-stable
[13761:13797:0627/083740.479124:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[13761:13797:0627/083740.479163:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[13798:13798:0627/083740.515594:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
Sat Jun 27 08:37:41 2020 RESOLVE: Cannot resolve host address: nz.privateinternetaccess.com:1198 (Temporary failure in name resolution)
Sat Jun 27 08:37:41 2020 Could not determine IPv4/IPv6 protocol
Sat Jun 27 08:37:41 2020 SIGUSR1[soft,init_instance] received, process restarting
[13761:13797:0627/083745.198126:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[13761:13797:0627/083745.198152:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
Sat Jun 27 08:37:51 2020 RESOLVE: Cannot resolve host address: nz.privateinternetaccess.com:1198 (Temporary failure in name resolution)
Sat Jun 27 08:37:57 2020 RESOLVE: Cannot resolve host address: nz.privateinternetaccess.com:1198 (Temporary failure in name resolution)
Sat Jun 27 08:37:57 2020 Could not determine IPv4/IPv6 protocol
Sat Jun 27 08:37:57 2020 SIGUSR1[soft,init_instance] received, process restarting
Fontconfig error: Cannot load default config file: No such file: (null)
Sat Jun 27 08:38:06 2020 RESOLVE: Cannot resolve host address: nz.privateinternetaccess.com:1198 (Temporary failure in name resolution)
Sat Jun 27 08:38:12 2020 RESOLVE: Cannot resolve host address: nz.privateinternetaccess.com:1198 (Temporary failure in name resolution)
Sat Jun 27 08:38:12 2020 Could not determine IPv4/IPv6 protocol
Sat Jun 27 08:38:12 2020 SIGUSR1[soft,init_instance] received, process restarting
Sat Jun 27 08:38:23 2020 RESOLVE: Cannot resolve host address: nz.privateinternetaccess.com:1198 (Temporary failure in name resolution)
Sat Jun 27 08:38:29 2020 RESOLVE: Cannot resolve host address: nz.privateinternetaccess.com:1198 (Temporary failure in name resolution)
Sat Jun 27 08:38:29 2020 Could not determine IPv4/IPv6 protocol
Sat Jun 27 08:38:29 2020 SIGUSR1[soft,init_instance] received, process restarting
Sat Jun 27 08:38:40 2020 RESOLVE: Cannot resolve host address: nz.privateinternetaccess.com:1198 (Temporary failure in name resolution)
Sat Jun 27 08:38:46 2020 RESOLVE: Cannot resolve host address: nz.privateinternetaccess.com:1198 (Temporary failure in name resolution)
Sat Jun 27 08:38:46 2020 Could not determine IPv4/IPv6 protocol
Sat Jun 27 08:38:46 2020 SIGUSR1[soft,init_instance] received, process restarting
 2020-06-27T00:38:50.102Z DEBUG vopono::openvpn           > Killed OpenVPN (pid: 13756)
 2020-06-27T00:38:50.102Z DEBUG vopono::util              > ip link delete _pia_nz_d
[0627/083850.104156:ERROR:nacl_helper_linux.cc(308)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly
 2020-06-27T00:38:50.164Z DEBUG vopono::util              > iptables -t nat -D POSTROUTING -s 10.200.1.0/24 -o eth0 -j MASQUERADE
 2020-06-27T00:38:50.165Z DEBUG vopono::util              > ip netns delete vopono_pia_nz
```

**Comment by cjordan** [comment] 2020-06-27 00:49
Forgot to say, I'm running up-to-date arch, and I installed `vopono` with `yay -S vopono-git`.

**Comment by jamesmcm** [comment] 2020-06-27 09:08
Did you try with another server?

The issue is:

> Sat Jun 27 08:37:35 2020 RESOLVE: Cannot resolve host address: nz.privateinternetaccess.com:1198 (Temporary failure in name resolution)

So I think either the server was temporarily down, or there's an issue with the DNS (which should be set to 8.8.8.8 at the moment inside the namespace).

Can you check you can connect to Google's public DNS normally too? i.e. if you run:

```bash
echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
```

Can you still connect to websites normally?

**Comment by jamesmcm** [comment] 2020-06-27 11:55
Also are you using an ethernet connection for your normal internet connection? Could you please paste the output of `ip addr`

**Comment by cjordan** [comment] 2020-06-30 00:44
Thanks for getting back to me, and sorry for my delayed reply - I'm gonna blame the Steam sale here...

Changing my nameserver in resolv.conf from my router (192.168.0.1) to 8.8.8.8 doesn't affect my ability to access websites.  My `ip addr`:
```
$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 04:d9:f5:05:08:29 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.20/24 brd 192.168.0.255 scope global dynamic noprefixroute eth0
       valid_lft 83360sec preferred_lft 83360sec
    inet6 fe80::f791:8eec:8b86:b670/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
```

I am using ethernet on this desktop, and I have tried other PIA servers (Netherlands and Japan) but these also failed to resolve.  I have no issue using openvpn normally, so I'm quite confused as to what could be happening.

Unrelated to this issue, but when I tried other servers like Brazil, `vopono` would say that the server alias does not exist (which is fine), but leaves a netns behind.  I'd be happy to chip in with the code once I've got my own issue cleared up.

**Comment by jamesmcm** [comment] 2020-06-30 08:05
Hmm, it's weird, I set it up to use the PIA DNS with the latest commits, but it seems to be an issue prior to that. I had the same issue when setting up the OpenVPN killswitch and accidentally blocking the destination port for UDP.

Are you able to connect with OpenVPN normally with UDP? It must either be an issue with the UDP connection, or the firewall rules. I plan to add TCP support soon so we can test that too, on the latest version you could modify the config file in `~/.config/vopono/pia/openvpn/` to use `proto tcp` and the port to 502 in serverlist.csv for NZ (use `--no-killswitch` when trying this).

You could also try using the .ovpn config file as  a custom provider, i.e. download them from https://www.privateinternetaccess.com/pages/download (the OpenVPN part at the bottom) and then run:

```bash
vopono -v exec --custom ./openvpn/New\ Zealand.ovpn --protocol openvpn "firefox"
```

For both the UDP and TCP configurations (be sure to use `--no-killswitch` for the TCP one at the moment).

> vopono would say that the server alias does not exist (which is fine), but leaves a netns behind.

Yeah, in theory it should clean up with Drop, but any panic will cause it not to trigger the destructors. However, vopono will clean up these dead namespaces on the next run (with the latest commits). It'd be good to fix all the cases where that can happen, but it's hard to track them down!

Does a Brazilian server exist btw? I don't see it in the config files I download.

**Comment by cjordan** [comment] 2020-07-02 00:20
Hi again, thanks for your patience!

> Hmm, it's weird, I set it up to use the PIA DNS with the latest commits, but it seems to be an issue prior to that. I had the same issue when setting up the OpenVPN killswitch and accidentally blocking the destination port for UDP.
> 
> Are you able to connect with OpenVPN normally with UDP? It must either be an issue with the UDP connection, or the firewall rules. I plan to add TCP support soon so we can test that too, on the latest version you could modify the config file in `~/.config/vopono/pia/openvpn/` to use `proto tcp` and the port to 502 in serverlist.csv for NZ (use `--no-killswitch` when trying this).

Yep, this works just fine:

`sudo openvpn /etc/openvpn/client/New_Zealand.conf`

> 
> You could also try using the .ovpn config file as a custom provider, i.e. download them from https://www.privateinternetaccess.com/pages/download (the OpenVPN part at the bottom) and then run:
> 
> ```shell
> vopono -v exec --custom ./openvpn/New\ Zealand.ovpn --protocol openvpn "firefox"
> ```
> 
> For both the UDP and TCP configurations (be sure to use `--no-killswitch` for the TCP one at the moment).
 
Unfortunately the UDP and TCP configurations I directly downloaded from the PIA website also did not resolve the nz server.

Is there any way to debug this further?  I'm not a network guru, but I'm really not doing anything funky with my home setup or desktop.

> > vopono would say that the server alias does not exist (which is fine), but leaves a netns behind.
> 
> Yeah, in theory it should clean up with Drop, but any panic will cause it not to trigger the destructors. However, vopono will clean up these dead namespaces on the next run (with the latest commits). It'd be good to fix all the cases where that can happen, but it's hard to track them down!

Again, I'd be happy to help, in particular because I think this package has great potential, and it's always good to see another useful Rust package.

> Does a Brazilian server exist btw? I don't see it in the config files I download.

Huh, looks like it got removed about a year ago.  New Zealand is definitely there, though.

**Comment by jamesmcm** [comment] 2020-07-02 08:06
> Unfortunately the UDP and TCP configurations I directly downloaded from the PIA website also did not resolve the nz server. 

It must be an issue with the firewall rules I think. Do you have `ufw` running or anything else that might interfere?

A good debugging step would be to run:

```bash
vopono -v exec --provider privateinternetaccess --server nz --protocol openvpn "bash"
```

And then inside the bash instance inside the network namespace run:

```bash
ip addr
ip link
sudo iptables -S
cat /etc/resolv.conf
cat /etc/netns/vopono_pia_nz/resolv.conf
```

Also run them outside the network namespace for a comparison.

You can also check whether you are able to ping the destination end of the veth pair from inside the network namespace (i.e. can you connect to your normal environment outside the namespace), if you get the ip from ip link and then try to ping that address from inside.


> Again, I'd be happy to help, in particular because I think this package has great potential, and it's always good to see another useful Rust package.

Thanks! I'm not sure what the issue is there exactly, but the relevant code starts here:

https://github.com/jamesmcm/vopono/blob/2094c016551a1e7177c5c46c6da5f683e6908ff1/src/vpn.rs#L113

You can see it returns an Err() rather than panicking though, which is propagated upwards, and should eventually result in it triggering Drop rather than panicking. I'll try to check it in more detail when I get some time, as it's an easy case to test as well.

**Comment by jamesmcm** [comment] 2020-07-04 11:24
The failure to cleanup on a missing server name is fixed in this commit btw: https://github.com/jamesmcm/vopono/commit/b75442023c8f9494caa0cc709ca61c7c8e226f1f

**Comment by cjordan** [comment] 2020-07-05 02:55
Nope, no firewall running, no `ufw`.

I've run the following with the up-to-date `vopono`.

Inside
```
chj@betelgeuse:~$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
13: _pia_nz_s@if14: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether ca:70:02:27:f4:93 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.200.1.2/24 scope global _pia_nz_s
       valid_lft forever preferred_lft forever
    inet6 fe80::c870:2ff:fe27:f493/64 scope link
       valid_lft forever preferred_lft forever
chj@betelgeuse:~$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
13: _pia_nz_s@if14: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether ca:70:02:27:f4:93 brd ff:ff:ff:ff:ff:ff link-netnsid 0
chj@betelgeuse:~$ sudo iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
chj@betelgeuse:~$ cat /etc/resolv.conf
nameserver 8.8.8.8
chj@betelgeuse:~$ cat /etc/netns/vopono_pia_nz/resolv.conf
nameserver 8.8.8.8
chj@betelgeuse:~$ Sun Jul  5 10:47:55 2020 RESOLVE: Cannot resolve host address: nz.privateinternetaccess.com:1198 (Temporary failure in name resolution)
Sun Jul  5 10:48:01 2020 RESOLVE: Cannot resolve host address: nz.privateinternetaccess.com:1198 (Temporary failure in name resolution)
Sun Jul  5 10:48:01 2020 Could not determine IPv4/IPv6 protocol
Sun Jul  5 10:48:01 2020 SIGUSR1[soft,init_instance] received, process restarting
Sun Jul  5 10:48:12 2020 RESOLVE: Cannot resolve host address: nz.privateinternetaccess.com:1198 (Temporary failure in name resolution)
```

Outside
```
chj in ~ at 20-07-05 10:49
$ ip addr
ip link
sudo iptables -S
cat /etc/resolv.conf
cat /etc/netns/vopono_pia_nz/resolv.conf
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 04:d9:f5:05:08:29 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.20/24 brd 192.168.0.255 scope global dynamic noprefixroute eth0
       valid_lft 79030sec preferred_lft 79030sec
    inet6 fe80::f791:8eec:8b86:b670/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
14: _pia_nz_d@if13: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether d2:84:6a:33:37:bc brd ff:ff:ff:ff:ff:ff link-netns vopono_pia_nz
    inet6 fe80::d26c:11c1:29b3:9be5/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 04:d9:f5:05:08:29 brd ff:ff:ff:ff:ff:ff
14: _pia_nz_d@if13: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether d2:84:6a:33:37:bc brd ff:ff:ff:ff:ff:ff link-netns vopono_pia_nz
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
# Generated by NetworkManager
nameserver 192.168.0.1
nameserver 8.8.8.8
```

> You can also check whether you are able to ping the destination end of the veth pair from inside the network namespace (i.e. can you connect to your normal environment outside the namespace), if you get the ip from ip link and then try to ping that address from inside.

Not sure what you mean here.

By the way, another small issue I've found is that `vopono` assumes that the user's default group is also the user's username.  It's quite easy to fix, and I can send a PR once we've worked out what's wrong here.

**Comment by jamesmcm** [comment] 2020-07-05 10:25
Here is the output on my machine for TigerVPN OpenVPN for comparison, with the latest code:

Inside:
```
$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 100
    link/none
    inet 100.97.0.4/16 brd 100.97.255.255 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::6579:8f1a:75da:94c4/64 scope link stable-privacy
       valid_lft forever preferred_lft forever
3: tig_us_s@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 92:1b:79:6e:20:75 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.200.1.2/24 scope global tig_us_s
       valid_lft forever preferred_lft forever
    inet6 fe80::901b:79ff:fe6e:2075/64 scope link
       valid_lft forever preferred_lft forever
```

Outside:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp0s31f6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 9c:5c:8e:77:9a:02 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.49/24 brd 192.168.1.255 scope global dynamic noprefixroute enp0s31f6
       valid_lft 40493sec preferred_lft 35093sec
    inet6 fe80::e031:aebf:7392:a7db/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
    inet6 fe80::6c26:cc7e:817d:f30d/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
4: tig_us_d@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 62:87:a0:3d:a9:b1 brd ff:ff:ff:ff:ff:ff link-netns vopono_tig_us
    inet 10.200.1.1/24 scope global tig_us_d
       valid_lft forever preferred_lft forever
    inet6 fe80::6087:a0ff:fe3d:a9b1/64 scope link
       valid_lft forever preferred_lft forever

```

Note that my veth pair (tig_us_s and  tig_us_d) has IPv4 addresses assigned, this is almost certainly the issue:

> inet 10.200.1.2/24 scope global tig_us_s
> valid_lft forever preferred_lft forever

and 

> inet 10.200.1.1/24 scope global tig_us_d
> valid_lft forever preferred_lft forever

In your case the destination veth is not assigned the IP 10.200.1.1:

>14: _pia_nz_d@if13: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether d2:84:6a:33:37:bc brd ff:ff:ff:ff:ff:ff link-netns vopono_pia_nz
    inet6 fe80::d26c:11c1:29b3:9be5/64 scope link noprefixroute
       valid_lft forever preferred_lft forever

This implies that it is the IP address allocation that is failing, your log seems fine though:

```
ip addr add 10.200.1.1/24 dev _pia_nz_d
ip netns exec vopono_pia_nz ip addr add 10.200.1.2/24 dev _pia_nz_s
ip netns exec vopono_pia_nz ip route add default via 10.200.1.1 dev _pia_nz_s
iptables -t nat -A POSTROUTING -s 10.200.1.0/24 -o eth0 -j MASQUERADE
```
Could you try to run 

```bash
$ sudo ip addr add 10.200.1.1/24 dev _pia_nz_d
```

Whilst vopono is running? Is anything else using that IP address?

As checking the code there is an assumption that this IP address would only ever be used by veth pairs, which needn't be true, but if the IP isn't being used by the local machine directly I'm not sure how we can check if the allocation will cause issues. Especially since it isn't throwing an error here.

So please try to run that manually when the namespace is running and see if you get any error message we might be able to use.

---------------------------------
For completeness here are my iptables outputs too:

Inside (with killswitch):
```
$ sudo iptables -S
-P INPUT DROP
-P FORWARD DROP
-P OUTPUT DROP
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -i tun+ -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
-A OUTPUT -d 8.8.8.8/32 -j ACCEPT
-A OUTPUT -d 8.8.4.4/32 -j ACCEPT
-A OUTPUT -p udp -m udp --dport 1194 -j ACCEPT
-A OUTPUT -o tun+ -j ACCEPT
-A OUTPUT -j REJECT --reject-with icmp-net-unreachable
```

Outside (check the masquerade rule exists!):
```
$ sudo iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
MASQUERADE  all  --  10.200.1.0/24        anywhere
```
Also, are you running your own DNS server? It seems your main DNS server is `nameserver 192.168.0.1` ? I don't think this is causing the issue (since you can use the internet normally) but you might want to remove that just to check.

**Comment by jamesmcm** [comment] 2020-07-05 10:25
> By the way, another small issue I've found is that vopono assumes that the user's default group is also the user's username. It's quite easy to fix, and I can send a PR once we've worked out what's wrong here.

And thanks for spotting this! Fixed in https://github.com/jamesmcm/vopono/commit/a77ba5fde72df14cdd2d055627f9ee540f25642e

**Comment by cjordan** [comment] 2020-07-06 05:32
Thanks once again for your patience, and making another git commit.

> $ sudo ip addr add 10.200.1.1/24 dev _pia_nz_d

This worked like a charm! (I just needed to use `pia_nz_d` instead).  Germany also worked ("de").  Once I issued that `ip addr add` command, it just springs to life.

To answer your other questions, no, I don't have my own DNS server (`192.168.0.1` is just my router), and I'm not using the `10.200.xxx.xxx` IP range for anything on my desktop (in fact, I'm only using `192.168.0.xxx` for the local network, and nothing else).  However, there is one thing I did spot just now - my little network manager applet spins as if connecting when I launch `vopono`.  It looks like network manager is trying to assign an IP address to the visible veth interface; maybe that is the issue?  Otherwise, I have no idea what could cause the problem.  I don't think you could have a setup less interesting than mine.  I use network manager just in case I want to do something with tethering and/or bluetooth.  The vast majority of the time it just gets a DHCP IP address, which I've statically assigned in my router's config.

**Comment by jamesmcm** [comment] 2020-07-06 07:12
Awesome, I'll try to do some tests with NetworkManager as I imagine that is the issue!

We could also add an extra check prior to launching OpenVPN / Wireguard.

**Comment by jamesmcm** [comment] 2020-07-07 19:18
Okay, hopefully this is worked around with this extra check: 

https://github.com/jamesmcm/vopono/commit/c896b621ecfde7b411898b157fecd48ede763549#diff-639fbc4ef05b315af92b4d836c31b023R194-R197

Please test it, as I'm worried if it tries to re-assign IPs when some of them already have the IPs assigned it might fail still.

**Comment by cjordan** [comment] 2020-07-09 01:16
Sorry for the delay, and thanks for the commit.  Unfortunately this didn't have any effect; I still need to run `ip addr add` to the `pia_nz_d` dev.

I feel quite helpless because I don't really understand the guts of the networking at play.  I only really understand basic stuff like setting up a home network.  But, is there something I could play with in the code to get results?  I'm just conscious of you potentially firing off commits that don't work for me, wasting your time.

**Comment by jamesmcm** [comment] 2020-07-09 09:15
Sure, the relevant code is the `add_routing()` method of `NetworkNamespace`:
https://github.com/jamesmcm/vopono/blob/c896b621ecfde7b411898b157fecd48ede763549/src/netns.rs#L117-L159

Could you try running the ip command as root?

```bash
sudo su
ip addr add 10.200.1.1/24 dev pia_nz_d
```

This is exactly what vopono runs.

**Comment by cjordan** [comment] 2020-07-11 02:43
Good news!  By doing what I should've done in the first place (consult the NetworkManager entry on the archwiki), I found that [ignoring specific devices](https://wiki.archlinux.org/index.php/NetworkManager#Ignore_specific_devices) made everything work.  Specifically in  /etc/NetworkManager/conf.d/unmanaged.conf:

```
[keyfile]
unmanaged-devices=interface-name:pia_nz_d
```

So, I think this wild goose chase is all NetworkManager's fault, and I apologise once more for making you jump through hoops.  Maybe it's worth putting this info up on the README to help others in the future.

I did try digging around in the Rust code, but figured something was wrong with my system when it was the `ip netns exec` line that hung, even though the `ip addr add 10.200.1.1/24 dev pia_nz_d` command was executed just before. NM must decide to override new a netns when it sees one, or something.

Thanks again for your help.  Please feel free to close.

**Comment by jamesmcm** [comment] 2020-07-11 08:19
Thanks! 

It's strange for me NetworkManager doesn't detect the veth pair at all. I wonder if it depends on the plugins installed.

Maybe we could create that file if the dir exists to ensure it doesn't try to override the assignment.

**Comment by jamesmcm** [comment] 2020-07-11 13:35
This should be done automatically with the latest commit :slightly_smiling_face: 

https://github.com/jamesmcm/vopono/commit/9f452f5ab11ab8e9e31f1c697cac3e96a58fd895#diff-a110dbf1a6b98055fbae68917f4ebfc9R32-R66

**Comment by cjordan** [comment] 2020-07-12 01:17
It works!  I can see the file being created.  Thanks once again.

**Comment by jamesmcm** [comment] 2020-07-12 15:02
Awesome, please test it is applied okay and I'll close the issue :slightly_smiling_face:

**Comment by cjordan** [comment] 2020-07-13 01:19
Yep, everything looks good, even after a reboot.  Thanks again!  Please close if you want to close.

**Comment by jamesmcm** [comment] 2020-07-13 08:39
Awesome, thanks!

**Closed by jamesmcm** 2020-07-13 08:39 UTC
